services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # drop on prod
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2
    ports:
      - "6379:6379" # drop on prod

volumes:
  db_data: